base_model: timm/vit_base_patch16_224.augreg2_in21k_ft_in1k
training_type: rag
version: 
trainer: 
  dropout: 0
  epoch: 10
  lr: 0.0001
  swa: 0.01
  decay: 0.01
dataloader:
  name: local/pets
  shot: 
  augmentation: []
  batch_size: 25
