base_model: timm/vit_base_patch16_224.augreg2_in21k_ft_in1k
training_type: liner_probing
version: 
trainer: 
  dropout: 0.5
  epoch: 100
  lr: 0.0001
  swa: 0.01
  decay: 0.01
dataloader:
  name: local/tongue_mask
  shot: 
  augmentation: []
  batch_size: 25
